// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0PWRJ0Qo2yx9dW8LSQ3rwsRCjwUvQ17U',
    appId: '1:448821904411:web:06d81e3180ee2b6e43a4be',
    messagingSenderId: '448821904411',
    projectId: 'fir-5b078',
    authDomain: 'fir-5b078.firebaseapp.com',
    storageBucket: 'fir-5b078.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Xg-7npSuHf7F87ORyBeFnT1I7I9siVo',
    appId: '1:448821904411:android:8672503f43de2c0743a4be',
    messagingSenderId: '448821904411',
    projectId: 'fir-5b078',
    storageBucket: 'fir-5b078.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXVtPkXoTR4VliL7IrNfkqszv6iFJ5pTk',
    appId: '1:448821904411:ios:469b431610cded9e43a4be',
    messagingSenderId: '448821904411',
    projectId: 'fir-5b078',
    storageBucket: 'fir-5b078.firebasestorage.app',
    iosBundleId: 'com.example.financemanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXVtPkXoTR4VliL7IrNfkqszv6iFJ5pTk',
    appId: '1:448821904411:ios:469b431610cded9e43a4be',
    messagingSenderId: '448821904411',
    projectId: 'fir-5b078',
    storageBucket: 'fir-5b078.firebasestorage.app',
    iosBundleId: 'com.example.financemanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0PWRJ0Qo2yx9dW8LSQ3rwsRCjwUvQ17U',
    appId: '1:448821904411:web:27c2ee009065db7743a4be',
    messagingSenderId: '448821904411',
    projectId: 'fir-5b078',
    authDomain: 'fir-5b078.firebaseapp.com',
    storageBucket: 'fir-5b078.firebasestorage.app',
  );
}
